# Uncomment this line to define a global platform for your project
platform :ios, '11.0'

source 'https://github.com/CocoaPods/Specs.git'

SDK_VERSION='6.2.2'

target 'ZendriveSDKDemo' do
  use_frameworks!
  pod 'ZendriveSDK', :git => 'https://bitbucket.org/zendrive-root/zendrive_cocoapod.git', :tag => SDK_VERSION
  pod 'MBProgressHUD', '~> 1.1.0'
end

target 'Testing-ZendriveSDKDemo' do
  use_frameworks!
  pod 'ZendriveSDK/Testing', :git => 'https://bitbucket.org/zendrive-root/zendrive_cocoapod.git', :tag => SDK_VERSION
  pod 'MBProgressHUD', '~> 1.1.0'
end
