platform :ios, '13.0'

source 'https://github.com/CocoaPods/Specs.git'

SDK_VERSION='10.0.0'


target 'ZendriveSDKDemoSwift' do
  use_frameworks!
  pod 'ZendriveSDK', :git => 'https://bitbucket.org/zendrive-root/zendrive_cocoapod.git', :tag => SDK_VERSION
  pod 'ZendriveSDKSwift', :git => 'https://bitbucket.org/zendrive-root/zendrive_cocoapod.git', :tag => SDK_VERSION
  pod 'CocoaLumberjack/Swift'
  pod 'MBProgressHUD', '~> 1.1.0'
end
