platform :ios, '10.0'

source 'https://github.com/CocoaPods/Specs.git'

SDK_VERSION='6.1.0'


target 'ZendriveSDKDemoSwift' do
  use_frameworks!
  pod 'ZendriveSDK', :git => 'https://bitbucket.org/zendrive-root/zendrive_cocoapod.git', :tag => SDK_VERSION
  pod 'ZendriveSDKSwift', :git => 'https://bitbucket.org/zendrive-root/zendrive_cocoapod.git', :tag => SDK_VERSION
  pod 'CocoaLumberjack/Swift'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'Crashlytics'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
    end
  end
end
